name: Python Lint

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install flake8 and black
        run: pip install flake8 black

      - name: Run flake8 (code style check)
        run: flake8 .

      - name: Run black (format check)
        run: black --check .
